// GENERATED from src/x402/open-catalog.ts by scripts/sdk/sync-sdk.ts — do not edit here.
// The canonical module is the one FlareClaw runs in production; this is a copy so
// that what we publish and what we run cannot diverge. Edit the canonical file.

/**
 * The x402 Open Catalog — a decentralized, attestation-aware x402 index.
 * (Community-run; independent of the x402 Foundation and of Coinbase.
 * Named for the ecosystem it serves, not the operator that runs it —
 * anyone can rebuild this catalog from public data, which is the point.)
 *
 * The ecosystem's only "directory" today is the CDP Bazaar, and listing
 * there requires settling through Coinbase's facilitator (measured
 * 2026-08-06: all 14,506 resources; a resource on any other facilitator
 * cannot be listed at all). That is vendor inventory, not an index.
 *
 * This catalog is the open counterpart, built from three provenance-
 * tagged sources, every entry re-derivable by anyone:
 *
 *   - `bazaar-mirror` — the CDP Bazaar's own public API, mirrored with
 *     attribution. Their catalog is public data; the spec says curated
 *     lists are caches that "can be regenerated by crawling". We are
 *     the regeneration.
 *   - `discovery`     — domains resolved per the x402 `discovery`
 *     extension (#2979): DNS TXT → /.well-known/x402 → live /supported,
 *     peers traversed breadth-first. This is the lane the Bazaar
 *     structurally excludes — and the only lane that carries
 *     ATTESTATION data, because discovery manifests declare it and we
 *     verify whether the claim is independently checkable.
 *
 * What this deliberately is NOT: an endorsement list. Source, freshness
 * and attestation status ride on every entry so a consumer can apply
 * its own policy; "discovery is not endorsement" holds here exactly as
 * it does in the spec.
 */

import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { resolveX402 } from './discovery.js';

const BAZAAR_URL = 'https://api.cdp.coinbase.com/platform/v2/x402/discovery/resources';
const DEFAULT_STATE_FILE = '.flareclaw/open-catalog.json';

/** Bounded mirror: far above today's 14.5k, far below a memory problem. */
const MIRROR_CAP = 30_000;
/** Discovery crawl bounds per refresh. */
const CRAWL_MAX_DOMAINS = 50;
const CRAWL_MAX_DEPTH = 2;
/**
 * Frontier diversity by registrable domain (spec, per the meloliva14
 * census): the 32-entry peers cap bounds fan-out per manifest but
 * nothing per operator — four censused single-operator domains each
 * hold 32+ hosts, so a crawler seeded inside such a fleet would walk a
 * full frontier without ever leaving it. Bounding visits per
 * registrable domain keeps the crawl measuring the network, not one
 * operator's fleet.
 */
const CRAWL_MAX_PER_REGISTRABLE = 4;

/**
 * Shared-platform suffixes treated as PUBLIC: the name directly above
 * each entry is a DIFFERENT operator deploying on the same platform.
 * Without this, last-two-labels hands 202 independent vercel.app
 * deployments ONE operator's crawl budget — the most diverse quarter
 * of the censused network (394/1,521 hosts, meloliva14 #2979) gets the
 * tightest cap, inverting the diversity rule's intent.
 *
 * Each entry is NOT a raw suffix — it is the DEPTH at which a new
 * operator begins, and that depth differs per platform (meloliva14's
 * railway catch): Cloudflare accounts sit directly under `workers.dev`
 * (the worker name above the account is not a new operator), while
 * Railway tenants sit under `up.railway.app` — listing `railway.app`
 * would collapse 66 tenants into one `up.railway.app` bucket, the
 * same merge this list exists to prevent, one level down. Cloud Run
 * has the identical shape at `a.run.app` (every censused host is
 * `*.a.run.app` — including the network's largest payer, so not a
 * corner nobody occupies). Test for a new entry: does the label
 * directly above it change hands between unrelated parties? If it
 * does, the boundary is BELOW it, not at it — and RUN THE TEST AS A
 * SCRIPT over census data; that is what caught the second case in a
 * minute (meloliva14). The wildcard-DNS mappers (`sslip.io`,
 * `nip.io`) are listed for a DIFFERENT reason: every name under them
 * resolves for whoever asks and there is no account level at all, so
 * the operator-boundary test does not apply — they are here so each
 * name stands alone. Hardcoded rather than a PSL dependency
 * (zero-dependency rule); needs occasional updating as platforms
 * appear in the wild.
 */
const PLATFORM_SUFFIXES = [
    'vercel.app', 'workers.dev', 'up.railway.app', 'onrender.com', 'fly.dev',
    'replit.app', 'netlify.app', 'a.run.app', 'sslip.io', 'nip.io',
];

/**
 * Registrable domain: last two labels, EXCEPT one more label is kept
 * above a shared-platform suffix (the tenant is the operator there).
 * Still not a full PSL lookup; for multi-level ccTLD suffixes (co.uk)
 * this under-splits, which errs toward MORE diversity enforcement.
 */
export function registrableDomainOf(domain: string): string {
    const clean = domain.toLowerCase().replace(/\.$/, '');
    for (const suffix of PLATFORM_SUFFIXES) {
        if (clean.length > suffix.length + 1 && clean.endsWith('.' + suffix)) {
            const above = clean.slice(0, -(suffix.length + 1)).split('.');
            return `${above[above.length - 1]}.${suffix}`;
        }
    }
    return clean.split('.').slice(-2).join('.');
}

/** Domains we re-resolve every refresh; peers extend from here. */
export const SEED_DOMAINS = ['flareclaw.app', 'api.flareclaw.app', 'testnet.flareclaw.app'];

export interface MirrorEntry {
    resource: string;
    network: string;
    scheme?: string;
    asset?: string;
    payTo?: string;
    lastUpdated?: string;
}

export interface DiscoveredEntry {
    domain: string;
    via: 'dns-txt' | 'well-known';
    kind: string;
    baseUrl?: string;
    kinds: { scheme: string; network: string }[];
    resources: string[];
    /** True only when the attestation claim is independently checkable. */
    attestationVerifiable: boolean;
    peers: string[];
    lastVerified: string;
}

export interface OpenCatalogState {
    mirror: MirrorEntry[];
    mirrorTotalUpstream: number;
    mirrorFetchedAt: string | null;
    discovered: DiscoveredEntry[];
    crawledAt: string | null;
}

export interface RefreshDeps {
    fetchImpl?: typeof fetch;
    /** Injected resolver (tests). Defaults to the real resolveX402. */
    resolver?: typeof resolveX402;
    statePath?: string;
    now?: () => string;
    seeds?: string[];
}

function emptyState(): OpenCatalogState {
    return { mirror: [], mirrorTotalUpstream: 0, mirrorFetchedAt: null, discovered: [], crawledAt: null };
}

// The state file is ~7MB at current mirror size; parsing it per public
// request would be a self-inflicted DoS. Cache the parsed state (and
// its sha256 — the snapshot digest consumers verify against) keyed by
// file mtime, so refreshes invalidate naturally and reads are free.
const stateCache = new Map<string, { mtimeMs: number; state: OpenCatalogState; digest: string }>();

export function loadCatalog(statePath = DEFAULT_STATE_FILE): OpenCatalogState {
    try {
        const mtimeMs = statSync(statePath).mtimeMs;
        const hit = stateCache.get(statePath);
        if (hit && hit.mtimeMs === mtimeMs) return hit.state;
        const raw = readFileSync(statePath);
        const state = JSON.parse(raw.toString('utf-8')) as OpenCatalogState;
        stateCache.set(statePath, {
            mtimeMs,
            state,
            digest: `sha256:${createHash('sha256').update(raw).digest('hex')}`,
        });
        return state;
    } catch {
        return emptyState();
    }
}

/** sha256 of the exact snapshot bytes being served — the re-derivation anchor. */
export function catalogSnapshotDigest(statePath = DEFAULT_STATE_FILE): string | null {
    loadCatalog(statePath);   // populate/refresh the cache entry
    return stateCache.get(statePath)?.digest ?? null;
}

function saveCatalog(state: OpenCatalogState, statePath: string): void {
    mkdirSync(dirname(statePath), { recursive: true });
    writeFileSync(statePath, JSON.stringify(state));
    stateCache.delete(statePath);   // next read re-parses + re-hashes
}

/**
 * Mirror the CDP Bazaar's public list. Failures leave the previous
 * mirror intact — a stale mirror with a timestamp beats an empty one.
 */
export async function refreshMirror(deps: RefreshDeps = {}): Promise<{ fetched: number; totalUpstream: number }> {
    const fetchImpl = deps.fetchImpl ?? fetch;
    const statePath = deps.statePath ?? DEFAULT_STATE_FILE;
    const now = deps.now ?? (() => new Date().toISOString());
    const state = loadCatalog(statePath);

    const mirror: MirrorEntry[] = [];
    let offset = 0;
    let totalUpstream = 0;
    for (;;) {
        const res = await fetchImpl(`${BAZAAR_URL}?limit=100&offset=${offset}`, {
            signal: AbortSignal.timeout(20_000),
        });
        if (!res.ok) throw new Error(`bazaar mirror fetch ${res.status} at offset ${offset}`);
        const page = (await res.json()) as {
            items?: Array<{ resource?: string; lastUpdated?: string; accepts?: Array<{ network?: string; scheme?: string; asset?: string; payTo?: string }> }>;
            pagination?: { total?: number };
        };
        const items = page.items ?? [];
        totalUpstream = page.pagination?.total ?? totalUpstream;
        for (const it of items) {
            if (typeof it.resource !== 'string') continue;
            const a = it.accepts?.[0] ?? {};
            mirror.push({
                resource: it.resource,
                network: a.network ?? 'unknown',
                ...(a.scheme ? { scheme: a.scheme } : {}),
                ...(a.asset ? { asset: a.asset } : {}),
                ...(a.payTo ? { payTo: a.payTo } : {}),
                ...(it.lastUpdated ? { lastUpdated: it.lastUpdated } : {}),
            });
            if (mirror.length >= MIRROR_CAP) break;
        }
        offset += items.length;
        if (items.length === 0 || offset >= totalUpstream || mirror.length >= MIRROR_CAP) break;
    }

    state.mirror = mirror;
    state.mirrorTotalUpstream = totalUpstream;
    state.mirrorFetchedAt = now();
    saveCatalog(state, statePath);
    return { fetched: mirror.length, totalUpstream };
}

/**
 * Crawl discovery records from the seed set, traversing peers
 * breadth-first. Every domain is resolved from scratch by the reference
 * resolver, so all of the extension's bounds and refusals apply; a
 * domain that fails simply doesn't appear this round (freshness is the
 * point — yesterday's entry must not survive on yesterday's proof).
 */
export async function refreshDiscovery(deps: RefreshDeps = {}): Promise<{ resolved: number; attempted: number }> {
    const statePath = deps.statePath ?? DEFAULT_STATE_FILE;
    const resolver = deps.resolver ?? resolveX402;
    const now = deps.now ?? (() => new Date().toISOString());
    const state = loadCatalog(statePath);

    const frontier: Array<{ domain: string; depth: number }> =
        (deps.seeds ?? SEED_DOMAINS).map(domain => ({ domain, depth: 0 }));
    const seen = new Set<string>();
    const perRegistrable = new Map<string, number>();
    const discovered: DiscoveredEntry[] = [];
    let attempted = 0;

    while (frontier.length > 0 && seen.size < CRAWL_MAX_DOMAINS) {
        const { domain, depth } = frontier.shift()!;
        if (seen.has(domain)) continue;
        // Frontier diversity: a fleet may not crowd out the rest of the
        // network. Seeds are exempt (depth 0 — the operator chose them).
        const reg = registrableDomainOf(domain);
        if (depth > 0 && (perRegistrable.get(reg) ?? 0) >= CRAWL_MAX_PER_REGISTRABLE) continue;
        perRegistrable.set(reg, (perRegistrable.get(reg) ?? 0) + 1);
        seen.add(domain);
        attempted++;
        try {
            const r = await resolver(domain, {
                ...(deps.fetchImpl ? { fetchImpl: deps.fetchImpl } : {}),
                noCache: true,
            });
            discovered.push({
                domain,
                via: r.via,
                kind: r.manifest.kind,
                ...(r.manifest.facilitator ? { baseUrl: r.manifest.facilitator.baseUrl } : {}),
                kinds: (r.liveKinds ?? r.manifest.facilitator?.kinds ?? [])
                    .map(k => ({ scheme: k.scheme, network: k.network })),
                resources: (r.manifest.resources ?? []).map(x => x.url),
                attestationVerifiable: r.attestationUsable === true,
                peers: r.peers ?? [],
                lastVerified: now(),
            });
            if (depth < CRAWL_MAX_DEPTH) {
                for (const p of r.peers ?? []) frontier.push({ domain: p, depth: depth + 1 });
            }
        } catch {
            // Unresolvable this round → absent this round. Negative
            // caching inside the resolver already rate-limits retries.
        }
    }

    state.discovered = discovered;
    state.crawledAt = now();
    saveCatalog(state, statePath);
    return { resolved: discovered.length, attempted };
}

export interface OpenCatalogQuery {
    source?: 'bazaar-mirror' | 'discovery';
    network?: string;
    attested?: boolean;
    limit?: number;
    offset?: number;
}

export interface OpenCatalogRow {
    source: 'bazaar-mirror' | 'discovery';
    resource: string;
    network: string;
    scheme?: string;
    attestationVerifiable?: boolean;
    lastSeen: string | null;
    /** How to re-derive this entry without trusting us. */
    provenance: string;
}

/** Unified, provenance-tagged view over both sources. */
export function queryCatalog(q: OpenCatalogQuery = {}, statePath = DEFAULT_STATE_FILE): {
    rows: OpenCatalogRow[];
    pagination: { limit: number; offset: number; total: number };
} {
    const state = loadCatalog(statePath);
    let rows: OpenCatalogRow[] = [];

    if (q.source !== 'bazaar-mirror') {
        for (const d of state.discovered) {
            const nets = d.kinds.map(k => k.network);
            rows.push({
                source: 'discovery',
                resource: d.baseUrl ?? `https://${d.domain}`,
                network: nets.join(',') || 'unknown',
                ...(d.kinds[0]?.scheme ? { scheme: d.kinds[0].scheme } : {}),
                attestationVerifiable: d.attestationVerifiable,
                lastSeen: d.lastVerified,
                provenance: `resolveX402("${d.domain}") — DNS TXT _x402.${d.domain} / https://${d.domain}/.well-known/x402`,
            });
        }
    }
    if (q.source !== 'discovery') {
        for (const m of state.mirror) {
            rows.push({
                source: 'bazaar-mirror',
                resource: m.resource,
                network: m.network,
                ...(m.scheme ? { scheme: m.scheme } : {}),
                lastSeen: state.mirrorFetchedAt,
                provenance: `${BAZAAR_URL} (public CDP Bazaar API, mirrored with attribution)`,
            });
        }
    }

    if (q.network) rows = rows.filter(r => r.network.split(',').includes(q.network!));
    if (q.attested === true) rows = rows.filter(r => r.attestationVerifiable === true);

    const offset = Math.max(0, q.offset ?? 0);
    const limit = Math.min(Math.max(1, q.limit ?? 50), 500);
    return { rows: rows.slice(offset, offset + limit), pagination: { limit, offset, total: rows.length } };
}

/** The headline numbers — the story in one object. */
export function catalogStats(statePath = DEFAULT_STATE_FILE): {
    name: string; independence: string;
    mirrored: number; mirrorTotalUpstream: number; mirrorFetchedAt: string | null;
    discovered: number; attested: number; crawledAt: string | null;
    networksExcludedByBazaar: string[];
    /** sha256 of the exact snapshot file being served; null before first refresh. */
    snapshotDigest: string | null;
} {
    const s = loadCatalog(statePath);
    const snapshotDigest = catalogSnapshotDigest(statePath);
    const bazaarNets = new Set(s.mirror.map(m => m.network));
    const excluded = [...new Set(
        s.discovered.flatMap(d => d.kinds.map(k => k.network)).filter(n => !bazaarNets.has(n)),
    )].sort();
    return {
        name: 'The x402 Open Catalog',
        independence: 'community-run; independent of the x402 Foundation and of Coinbase — every entry re-derivable from public data',
        mirrored: s.mirror.length,
        mirrorTotalUpstream: s.mirrorTotalUpstream,
        mirrorFetchedAt: s.mirrorFetchedAt,
        discovered: s.discovered.length,
        attested: s.discovered.filter(d => d.attestationVerifiable).length,
        crawledAt: s.crawledAt,
        networksExcludedByBazaar: excluded,
        snapshotDigest,
    };
}
